<template>
  <section class="content-card booking-page"><div class="page-title"><div><p class="eyebrow">ОНЛАЙН-ЗАПИСЬ</p><h1>Записаться на приём</h1><p>Последовательно выберите услугу, мастера, дату и время.</p></div></div>
    <div class="booking-steps"><span v-for="n in 4" :key="n" :class="{active:step>=n}">{{n}}</span></div>
    <div v-if="step===1"><h2>1. Выберите услугу</h2><div class="choice-grid"><button v-for="s in services" :key="s.id" class="choice-card" @click="chooseService(s)"><i class="pi pi-sparkles"></i><b>{{s.nazvanie}}</b><span>{{s.stoimost}} ₽ · {{s.prodolzhitelnost}} мин.</span></button></div></div>
    <div v-else-if="step===2"><Button label="Назад" text icon="pi pi-arrow-left" @click="step=1"/><h2>2. Выберите мастера</h2><div class="choice-grid"><button v-for="m in masters" :key="m.id" class="choice-card" @click="chooseMaster(m)"><i class="pi pi-user"></i><b>{{m.fio}}</b><span>{{m.specialnost}}</span><small>Пн–Пт, {{shortTime(m.nachalo_raboty)}}–{{shortTime(m.konec_raboty)}}</small></button></div></div>
    <div v-else-if="step===3"><Button label="Назад" text icon="pi pi-arrow-left" @click="step=2"/><h2>3. Выберите день</h2><input class="native-input" type="date" v-model="date" :min="today" @change="loadSlots"><Message v-if="date && !slots.length" severity="info" :closable="false">На этот день свободного времени нет. Выберите другой будний день.</Message><div class="slots"><Button v-for="slot in slots" :key="slot" :label="slot" :outlined="time!==slot" @click="time=slot"/></div><Button v-if="time" class="confirm-booking" label="Продолжить" icon="pi pi-arrow-right" iconPos="right" @click="step=4"/></div>
    <div v-else class="booking-summary"><h2>4. Подтвердите запись</h2><dl><div><dt>Услуга</dt><dd>{{service.nazvanie}}</dd></div><div><dt>Мастер</dt><dd>{{master.fio}}</dd></div><div><dt>Дата и время</dt><dd>{{formatDate(date)}}, {{time}}</dd></div><div><dt>Стоимость</dt><dd>{{service.stoimost}} ₽</dd></div></dl><Message v-if="error" severity="error" :closable="false">{{error}}</Message><div class="actions"><Button label="Назад" severity="secondary" @click="step=3"/><Button label="Записаться" icon="pi pi-check" @click="createBooking"/></div></div>
  </section>
</template>
<script>
import Button from 'primevue/button'; import Message from 'primevue/message'; import {useDataStore} from '@/stores/dataStore'
export default {components:{Button,Message},data:()=>({store:useDataStore(),step:1,services:[],masters:[],service:null,master:null,date:'',time:'',slots:[],error:''}),computed:{today(){return new Date().toISOString().slice(0,10)}},async mounted(){this.services=await this.store.get_bookable_services()},methods:{async chooseService(s){this.service=s;this.masters=await this.store.get_masters_for_service(s.id);this.step=2},chooseMaster(m){this.master=m;this.step=3},async loadSlots(){this.time='';this.slots=await this.store.get_available_slots(this.service.id,this.master.id,this.date)},async createBooking(){try{await this.store.create_booking({usluga_id:this.service.id,kosmetolog_id:this.master.id,date:this.date,time:this.time});this.$toast.add({severity:'success',summary:'Запись создана',detail:'Ожидайте подтверждения администратора',life:3500});this.$router.push('/my-bookings')}catch(e){this.error=e.response?.data?.message||'Не удалось создать запись'}},shortTime(v){return v?.slice(0,5)},formatDate(v){return new Date(v+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}}}
</script>
